language: node_js
node_js:
  - "6"
  
env:
  - BROWSER=firefox
  - BROWSER=chrome
  - BROWSER=safari
before_script:
  - npm run lint
  - sleep 15

script:
  - npm run test-e2e-travis

cache:
  directories:
    - node_modules
    
notifications:
  slack:
    secure: Wc0B0/aZmbTHul+ip7hM6clYffUxcAu2lDSd8iF4/lPuZAe3v9C5sqEdGT2uzJjoeVAKu2LaZ45V8to7psQPgh52VTLycR8glYq0lOCkHB1siGaRT/lfRMepcwuI9zUSpx1AQJYLe42tOXx6g+TF74GhwjFlubnV7z7e/rgMbwKAV7+xrPGtT6tV/YWigoEvQwHCabKToA5SSFVwdVRGVfOJyaIqvdLnbFz082Zu6NI0/cCoBA7zc8CX1Rbo1/e3mE4QeG9qvslBgOHgDf5uyjlrThyDe4/Pxk5KzH1Nnae1WKGjwRiP9Z2XxAchGTWfD7SBZ06CxMSDbxtREjqNcq4r0gkc+PCMJRbW6MwCRnZ4aYLgytCrTlfNz9YzRMr5mR4LR1WmWZJTHd3kPQjDljoM1Uj5JVbHFaeUkMCslct2p+W1fSZaRyks2/2sTEkCInfwYxzjP+p+B3jnBYvxrxhr0e+EahMQWBtUnbF8GoYalUQFFn1EjqUeN1hyewE9jwm1WLRUmfQY2sXfHNkph0adI1LGlVn76gvBzuAkNPlOBl9Rb4CmERK9DRQH6pDGFbibJQOFu0rCMy4dvRmYDRsVWQPUAP3WPDpXCryaI3aDXSNwwJy1+xYj/DH+RZPf+Qg8ld1fvKtwGkvD8MRKzbFzqDsauTtv+Cod5YJgwXo=

addons:
  sauce_connect: true
  
services: mongodb
